steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/tp-devops-401106/website-tools/current-image-wordpress:v2', '.' ]
images:
- 'us-central1-docker.pkg.dev/tp-devops-401106/website-tools/current-image-wordpress:v2'

